# =====温馨提示=====
# 此文件编码格式为UTF-8，请注意冒号后面有个空格，如遇到此文件出错，删除此文件即可重置。可以使用颜色代码。
# 本插件自动保存的功能和Bukkit自带的自动保存功能重复，建议把bukkit.yml中autosave的值改为0以节省服务器资源
# 不想要有公告/信息？冒号后不要留空，请这样 ''
# 作者：Wickham阿华

# =====登录系统=====
登陆系统: false
登录保持时间: 10
# 分钟

# =====自动保存=====
自动保存地图: true
自动保存地图时间间隔，单位分钟: 22

# =====自动公告=====
自动公告: false
自动公告时间间隔，单位分钟: 1
公告1: 欢迎来到Wickham的服务器
公告2: 欢迎来到Wickham的服务器
公告3: ''

# =====其他信息=====
玩家加入时给玩家的信息开关: false
玩家加入时给玩家的信息: 欢迎来到 Wickham 的服务器
玩家加入时的插件介绍: true

# =====玩家死亡=====
死亡是否保留背包内的物品: false
死亡后保留一半等级: false
# 默认不保留任何等级

# =====玩家升级=====
三十级后每升级一级加血量上限: false
最大血量上限: 40
# 两个血是一颗心
# 低于20不起作用

# =====地块保护=====
保护耕地不被踩坏: true
# 只能防止人为踩坏

# =====传送系统=====
非OP传送等待时间（秒）: 3
tpa请求等待时间（秒）: 20